= Adding and Editing Pages on GitHub
:doctype: book
:page-authors: Vector Hasting
:table-caption: Data Set
:imagesdir: /Media/Images/
:page-draft_complete: 25%
:page-stage: NoShow
:page-todos: Add images. Organize, organize, organize, KISS
:showtitle:

= Basic Changes: Working on GitHub Website

Note: there are many possible work-flows on GitHub, or any other git-enabled repository. 

For basic changes, like adding a single page or fixing minor typos, it is perhaps easiest to work straight in the GitHub Website interface. 

. You will need to navigate to the link:https://github.com/ProjectLiberty2029/ProjectLiberty2029.github.io/["GitHub Website for Project Liberty 2029.", window=read-later,opts="noopener,nofollow"] 
. Find the button near the top right that says "Fork," click it and follow the instructions to create your own copy of ProjectLiberty2029.github.io.
. Switch to that repository: this can be confusing at first: the original is https://github.com/**ProjectLiberty2029**/ProjectLiberty2029.github.io, but yours will be https://github.com/**YourUserName**/ProjectLiberty2029.github.io.
.. The reason for this is to insure what is called a "linear commit history," 


== Next Step Resources: 

Here are the other documents in this suite of docs for helping to on-board contributors. 

<</content/Contributing/010_Getting_Started_Helping.adoc#,Getting Started Contributing.>>

<</content/Contributing/020_Overview_Of_The_Environment.adoc#,Overview of the Environment.>>

(This document: Overview of the Environment.)

<</content/Contributing/040_How_To_Publish_Your_Edits.adoc#,How to Publish Your Contributions.>>

<</content/Contributing/050_Guidelines_for_Pages.adoc#,Guidelines and Standards for Pages.>>

<</content/Contributing/060_Sample_Document.adoc#,A Sample Document to Copy and Modify.>>

<</content/Contributing/070_FAQ.adoc#,FAQ: Frequently Asked Questions, and how to get more Help.>>

There is also a link:https://www.reddit.com/r/ProjectLiberty2029/["subreddit for discussion and support.", window=read-later,opts="noopener,nofollow"] 


