= Guidelines and Standards for Pages.
:doctype: book
:page-authors: Vector Hasting
:table-caption: Data Set
:imagesdir: /Media/Images/
:page-draft_complete: 0%
:page-stage: NoShow
:page-todos: This is just a copy of 010, write this page
:showtitle:

= Overview

This page is for those who are considering helping us improve the proposals here in the Project Liberty 2029 Wiki. 

==

Asciidoc has the following recommendations for best practices: 

. Type one line per sentence. 
.. Use "Soft Wrap" to make this easier. 
. See <</Page_Draft_Status.adoc#,Page Draft Status Guidelines>> for how to fill in the front-matter attribute for :page-draft_complete:
. See <</content/Contributing/060_Sample_Document.adoc#,the Sample Document for explanations of the Asciidoctor Front Matter.>>
. See <</content/Stages_Defined.adoc#,the Stages Defined >>for an explanation of which Stage of Struggle your document may relate to.
.. If you do not need your document to show in Stages of Struggle -- for example, it may be a subdocument, like this one -- then put "NoShow" for the :page-stage: front matter attribute. 
.. To control what order your page appears in any given stage, name the filename with the appropriate number: those sections sort by the name of the file.  
. If including images or figures, wherever possible include an image title. 

== How to get started?

Easing that complexity is the goal of this set of documents: 

<</content/Contributing/010_Getting_Started_Helping.adoc#,Getting Started Contributing.>>

<</content/Contributing/020_Overview_Of_The_Environment.adoc#,Overview of the Environment.>>

<</content/Contributing/030_How_To_Add_Or_Edit_Pages.adoc#,Adding and Editing Pages on GitHub.>>

<</content/Contributing/040_How_To_Publish_Your_Edits.adoc#,How to Publish Your Contributions.>>

(This document: Guidelines and Standards for Pages.)

<</content/Contributing/060_Sample_Document.adoc#,A Sample Document to Copy and Modify.>>

<</content/Contributing/070_FAQ.adoc#,FAQ: Frequently Asked Questions, and how to get more Help.>>

There is also a link:https://www.reddit.com/r/ProjectLiberty2029/["subreddit for discussion and support.", window=read-later,opts="noopener,nofollow"] 
