# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

title: Project Liberty 2029
description: >- # this means to ignore newlines until "baseurl:"
  Here you will find a blueprint for restoring and securing our Nation, which is dedicated to personal <br />
  Freedom and Justice, and to the proposition that a Nation so founded shall not perish from this earth. 

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ProjectLiberty2029.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  ProjectLiberty2029

github:
  repository_url: "https://github.com/ProjectLiberty2029/ProjectLiberty2029.github.io"

# Build settings
#theme: minima
#remote_theme: pages-themes/leap-day@v0.2.0
#remote_theme: https://github.com/ProjectLiberty2029/PL2029_theme
plugins:
  - jekyll-feed
  - jekyll-asciidoc
  - jekyll-sitemap
  - jekyll-seo-tag
#  - jekyll-remote-theme 
  
#
# Added for asciidoc processing:
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    icons: font
    idseparator: _
    stylesdir: css
    source-highlighter: coderay    


# Jekyll Collections for Liquid

collections:
  content:
    output: true
    sort_by: url
#    permalink: /:collection/:path/:name/


github: [metadata]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - LICENSE
  - README.adoc
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

