= First Lame Duck Session Dangers
:doctype: book
:table-caption: Data Set
:imagesdir: /Media/Images/
:page-authors: Vector Hasting
:page-draft_complete: 25%
:page-stage: 00
:page-todos:  
:showtitle:

= Who will be seated in the new congress?

There is a danger that the MAGA regime will not honor the Will of the People during the 2026 midterm elections. 
link:https://www.thebulwark.com/p/dirty-procedural-move-house-republicans-election-denial-2026-midterms["This article on the Bulwark Substack," , window=read-later,opts="noopener,nofollow"] explores this topic in detail.

While this has historically happened when the elections were so close as to be statistical ties, now the world is different because the reality of the vote count itself is being questioned. 
This means that even if erstwhile reasonable persons would have agreed that the vote count was a clear win, the MAGA regime may simply declare some pretense of fraud and proceed on such claims to throw out candidates from the opposing party.
Such a move requires only a bare majority vote in the current (119th) House of Representatives to refuse the credentials of a sufficient number of winning Democratic candidates in favor of their MAGA Republican opponent to hold onto power. 
Republicans might coalesce around this move because of fears of retribution by MAGA powers if they fail to go along. 

While this may seem to be a relatively low threat because of its historical rarity, it is nonetheless a high risk threat. 
It is high risk because the difference in a world where the MAGA regime retains control over both houses of Congress during the 120th session and one in which they do not can tip the balance of whether we have a constitutional break or not. footnotel[See: <</Election2028/The_Coming_Constitutional_Hack.adoc#,The coming Constitutional Hack.>>
Therefore we must make adequate plans. 

== Upholding the Will of the People, Part 1:

First and foremost, we need the largest electoral win possible in sufficient numbers of Republican districts so as to morally influence those memebers not to vote themselves into place. 

This is <</Election_2028/Before_The_Election/Before_The_Election_Overview.adoc#,described elsewhere in Project Liberty 2029.>> 

== Upholding the Will of the People, Part 2:

If it appears that despite an otherwise clear win, that Republicans are working toward not seating enough Democrats to retain control, then there will need to be mass protests in enough congresspersons's districts to change their minds. 
These protests will need to include enough work stoppages so as to put maximum pressure on donors to those Republicans who are planning to vote themselves into power despite the Will of the People. 

= If MAGA controls both houses of the 120th Congress:

There are two major forks in the road if we have not regained control of either house of the 120th Congress. 

== We won the votes but lost the Congress:  

If we find ourselves in this position in 2029 despite having won a clear majority, but after an all MAGA controlled Congress has been seated, then we must proceed to Plan B(a). 
That means mass demonstrations and strikes on industry that are not based on Unions: but on the People's Demand for Democracy. 
Achiving this will require having already discussed it publically in order to prepare The People to take these kinds of actions. 
Happily, this kind of preparation of the public dialog should increase the odds of having a legitimate 120th Congress seated in the first place. 

== MAGA got the votes to control Congress:

This is a doomsday scenario. 

It raises the likelyhood that MAGA will consolidate power with a new Pesidential candidate of their choice being sworn in as President in 2029. 

It should lead people to Plan C. 
