= Rename DOGE to ROLA
:doctype: book
:page-authors: Vector Hasting
:table-caption: Data Set
:imagesdir: /Media/Images/
:page-draft_complete: 75%
:page-stage: 11
:page-todos: Complete me. 
:showtitle:

## Overview

The "Department of Government Efficiency" was originally the US Digital Service which was put in place by President Barack Obama as a tool for supporting the government across all departments and agencies. Because of it's pan-governmental mandate and nature, it was used by DJT, the MAGA regime, and Project 2025 (the MAGA Regime) to perform hatchet jobs on US agencies.  

It was headed for several months by Elon Musk, who renamed it DOGE after a meme-coin with which he has long been associated. It ostensibly stands for "Department of Government Efficiency." This name is of questionable legal validity. 

DOGE implemented a far-ranging destruction of US government functions including the dismantling of USAid which has resulted (and will continue to result) in millions of horrible and preventable deaths worldwide due to starvation and disease. 

Because of this legacy of arguable crimes-against-humanity, DOGE must be eliminated. 

However, because of it's position as a fulcrum for change, the functions of DOGE must be preserved and used to repair as much as possible as quickly as possible in service of PG2029. 

Therefore, the President must by Executive Order rename DOGE to something else. We here recommend "ROLA: Restoration of Liberty Agency." 

## Activities & Resources

The President must appoint an individual to work much as Musk did to sweep into ROLA and root out loyalists to Must, DJT, and Project 2025 and their goals and ideals. 

[.lead]
Needed for completeness:

. Specific goals for ROLA: whereas DOGE accumulated information and shuttered agencies, this destructiveness only required a list of agencies. 
. We need a prioritized list of departments and agencies to reconstruct with:
.. plausible goals for such reconstruction.
.. personnel and functions to target (for example, restoring the Civil Rights Division at the FBI, under the Department of Justice)
.. defined goals (for example, restoring EPA oversight of carbon emissions)
.. lists of resources available on day-one,
.. lists of resources needed that will require congressional approval and/or funding. 

