= Replacing ICE
:doctype: book
:page-authors: Vector Hasting
:table-caption: Data Set
:imagesdir: /Media/Images/
:page-draft_complete: 75%
:page-stage: 11
:page-todos: Completeness. 
:showtitle:

The goal of TheRealProject2029 (TRP2029) is to map for We The People a comprehensive set of strategies and demands to Restore and Protect Democracy, Liberty and Justice. We will abbreviate those goals as the "Project Goals 2029," or PG2029. 
(Or a better abbreviation someone can suggest and we can all agree on.)

Human resources will be a major challenge for PG2029, because many people still in government will be either 1) untrustworthy employees from the previous administration, or 2) tainted by association with them. 

By 2029, ICE is probably the most destroyed institution of the US government. 

By 2029 ICE will have committed numerous crimes: +

. operating prisons with inhumane general conditions tantamount to torture,
. actual torture through physical and sexual abuse by ICE agents of people in their custody; we should expect this to be similar but worse than Abu Ghraib torture and prisoner abuse,
. actual murder of people in ICE custody; this will include first, second, and third degree murder,
. corruption, perhaps in the billions, due to access to unprecedented funds by unscrupulous leaders with a demoralized workforce, 
. collecting and holding information on US Citizens under color of authority to prosecute resistance to ICE's authority.

As a result, by 2029 ICE will have the popularity of radioactive waste. 

The Executive must not tolerate any erosion of its mandate to achieve PG2029, therefore it cannot use ICE in any capacity or risk being tarnished in the eyes of the public, and in the eyes of history, and in the actuality of corruption. 

Therefore, the Executive must move swiftly to achieve two goals: 

. find a replacement for the border control duties and customs enforcement duties of ICE; these are essential to protecting Americans from actual foreign threats, 
. prosecute ICE personnel where appropriate, keeping in mind the psychological facts of "The Lucifer Effect," and how a few people can lead many others into pathological behavior. 

## Finding the human resources to perform border/customs control functions
Implement a course of action that follows this outline:

(This section presumes that the Transportation Safety Administration has remained largely off the DJT administration's radar and been less corrupted)

. Use an Executive Order to transfer funds from ICE to TSA to use the customs knowledge contained at TSA to bolster the loss of personnel in ICE.
. Use an Executive Order to transfer funds from ICE to ROLA for the purposes of hiring trainers and analysts to assist with triage of personnel still at ICE. 
. Use those transferred funds to pay for hiring highly trained general purpose evaluators under ROLA to run several Tiger-teams dedicated to salvaging employees from ICE and TSA for legitimate use by the US Government.
. There will be a Tiger Team dedicated to Evaluation, which shall examine the records of individuals and their department and team activities to make a preliminary assessment of ICE and TSA personnel into three "Alignment Groups:"
.. Those who are loyal to the mission of DJT's regime, we shall call these Authoritarians,
.. Those who are trying to keep out of any political affiliation and just do their jobs, we shall call these Neutrals, 
.. Those who are predisposed or committed toward PG2029, we shall call these Patriots.
 . Once preliminary assessments of ICE and TSA alignments are made, personnel shall be assigned to a second ROLA tiger team for Deployment. 
 . This second ROLA Deployment team will have the following goals:
 .. Sideline to positions with negligible responsibility all employees in the Authoritarian group. Members of this group should not be fired for the following reasons:
 ... minimize the building of a resentment pool that will be dedicated to resurrecting Authoritarianism and opposing PG2029
 ... retaining institutional knowledge of the abuses under the Authoritarian regime of DJT
 ...  maintaining influence through their paychecks on members of this group in the hopes of having them participate in Renunciation. 
 .. Training the Patriots on how to train the Neutrals on how to repair damage done by ICE. 
 .. Deploying Aand . and ICE aliFocus on the use of whatever remains of training at TSA to aining The following Use an ExecThis will requires appropriately trained manpower that is also politically un-affiliated with the abuses of ICE. 

There will be a small number of ICE agents who have been left in administrative jobs during the abuses, and therefore potentially un-tainted by fieldwork. 
Reliably determining who these individuals are is a significant challenge in 2029


Therefore, and it will require 

Instead, the Executive must implement an immediate purge of ICE officials who are complicit in the crimes  while seeking Congress' approval to rename and reorganize ICE. 

Whatever ICE becomes , a top-down
