# The Coming Constitutional Hack
:doctype: book
:page-authors: Vector Hasting
:table-caption: Data Set
:imagesdir: /Media/Images/
:page-draft_complete: 75%
:page-stage: 06
:page-todos: Complete me. Probably add a map of Washington DC. 
:showtitle:


[.lead]
_"It's not who votes that counts, +
 it's who counts the votes." +
 -- Joseph Stalin._

## Overview

[.lead]
If you thought January 6th, 2021 was bad... the next January 6th will blow it out of the water.

We must expect the same playbook of faking presidential electors that was tried in 2021, but this time it will include the powers of the  Department of Justice (DOJ) and the US Military, currently still known as the Department of Defense (DOD), and the Department of Homeland Security (DHS). 

Based on current trends, it is extremely likely that there will be a massive vote in 2028 for the Presidential Candidate that opposes the DJT, MAGA, Project 2025 regime (the MAGA regime). 

We will call that person the Democratic candidate, since it is currently inconceivable that any other political party will have the capacity to win a nationwide election for president.  

At that point, it will be clear to large majorities of the public that crimes of serious magnitude were committed, and continue to be committed during the MAGA regime. 

However, there will also be an increasingly strident, intransigent, and also possibly violent, commitment by approximately 100 Million Americans in support of the MAGA regime. 

Faced with these facts, the MAGA regime is likely to use all strategies available to them to remain in power despite losing the popular and Electoral College vote for President, and control of the US Congress. 

[.lead]
How the MAGA regime can attempt to hack the US Constitution to 'Constitutionally' install an un-constitutional regime is explained here in detail. 

[.lead]
If you want the summaries, see  <<Summary of Points of Failure, Summary of the problem>> and <<Summary of the Defense, Summary of the Defense.>> 

## The Points Of Failure

Here is a review of how our convoluted Electoral College system of voting works:
[1]
. On November 7, 2028, we will use a Past-the-Post system in 48 states, and the candidate with the largest number of votes (not necessarily a majority) gets all the "Electors" from that state (except Maine and Nebraska). 
.. MAGA loyalists have already begun the process of increasing Gerrymandering and aggressively purging voter roles in order to "pick their voters" for the 2026 midterm elections, and will likely attempt more of the same during the 2028 election cycle. 
.. These voter-roll/voter-district hacks are very old, but are being employed with greater aggression. 
+
[2]
. Each state's Secretary of State certify the election results. Some of these officials are elected and answer to the people, and some are appointed and answer to the Governor. In either case, there are party loyalties for Secretaries of States.  
.. There have been moves by Secretaries of State in the past to immorally and/or illegally change outcomes by affecting such things as where lines will be long for voting and how aggressive certain voting requirements are enforced in different areas.  
+
[3]
. Each state's political parties prepares a list of "Electors," who are actual people who will be appointed by the Secretary of State to perform the job of casting the "Elector's votes" for the winning candidate.
+
[4]
. Those electors meet and sign and certify Elector Certificates granting their Electoral Votes to those candidates. (footnote:https://constitution.congress.gov/constitution/amendment-12/["12th Amendment to the US Constitution"])
.. Seven states engaged in a "fake elector scheme" in the 2020 election. footnote:https://en.wikipedia.org/wiki/Trump_fake_electors_plot Few people were held accountable. Therefore it is likely there will be a repeat of this kind of activity in the 2028 election.  
+
[5]
. Those Electors shall "transmit to seat of the government of the United States, directed to the President of the Senate" those Elector Certificates. footnote:[link:https://constitution.congress.gov/constitution/amendment-12/["12th Amendment to the US Constitution", window=read-later,opts="noopener,nofollow"]] The "President of the Senate" is the Vice-President of the United States footnote:[link:https://constitution.congress.gov/browse/essay/artI-S3-C4-1/ALDE_00001111/["US Constitution, Article I, Section 3, Clause 4", window=read-later,opts="noopener,nofollow"]]
.. Transmission of the fake elector certifications was a weakness in the 2020 fake elector plot, one which may well be more robust in 2028.
.. There are compounding mandates which can lead to competing claims: 
... The link:https://constitution.congress.gov/constitution/amendment-12/["12th Amendment to the US Constitution", window=read-later,opts="noopener,nofollow"] stipulates transmission of the Certificates to the "President of the Senate,"
... The link:https://en.wikipedia.org/wiki/Electoral_Count_Reform_and_Presidential_Transition_Improvement_Act_of_2022["Presidential Reform Act of 2022," ,window=read-later,opts="noopener,nofollow" ] stipulates transmission to the Archivist of the United States, which as of 2025 was Marco Rubio (in addition to his duties as Secretary of State),
... A MAGA regime which will stop at nothing to retain power will be able to use the Archivist clause of the Presidential Reform Act to create a "valid" set of Elector Certificates that reflect a (false) MAGA candidate win, while the version of Elector Certificates sent to the President of the Senate will be controlled (if not changed) by MAGA regime Vice-President JD Vance. 
+
[6]
. On January 3rd, the newly elected congress swears itself in and selects its leaders. 
.. Because this is 3 days in advance of the crucial January 6th Certification Date, if the MAGA regime wishes to weaken Congress to prevent them from Certifying an election that MAGA has lost, they could interfere with constituting Congress, and with select on Speaker and Senate Majority leader by using the National Guard Unit planned for in link:https://www.whitehouse.gov/presidential-actions/2025/08/additional-measures-to-address-the-crime-emergency-in-the-district-of-columbia/["DJT's August 25, 2025 Executive Order, ", window=read-later,opts="noopener,nofollow"] and arresting Congress members on fictional charges of Treason or Felony or Breach of the Peace (these are the exceptions to Congressional immunity from Arrest in the link:https://www.archives.gov/founding-docs/constitution-transcript["US Constitution Article I, Section 6, Clause 2.", window=read-later,opts="noopener,nofollow"]),  
+
[7]
. The link:https://constitution.congress.gov/constitution/amendment-12/["12th Amendment to the US Constitution", window=read-later,opts="noopener,nofollow"] dictates that on January 6th:
.. Both chambers must meet in a Joint Session, and 
.. The Joint Session must be presided over by the Vice-President, and
.. They will open and count the Elector Certificates, and 
.. If there is a candidate with a majority of those votes, then that candidate "shall be President," and 
.. If no candidate has a majority, then from the top three candidates, the House of Representatives will vote in a specific manner where each state gets one vote (determined by the members from that state, therefore determined by party-affiliation of that state). 
.. The plan to subvert this process was also tried on January 6th, 2025, but failed due to Mike Pence being unwilling to go along with the plan. 
.. JD Vance, however, has pledged to follow through on the use of the position of Vice President presiding over the Joint Session to affect the outcome of the election. 
... This became harder to do in the way DJT demanded Mike Pence perform it on January 6, 2021 because of the link:https://en.wikipedia.org/wiki/Electoral_Count_Reform_and_Presidential_Transition_Improvement_Act_of_2022["Presidential Reform Act of 2022," ,window=read-later,opts="noopener,nofollow" ] however, 
... While outright fraudulent substitution of the Elector Certificates was not successful on January 6th, this was because Mike Pence Refused to make the substitution. The danger now will be if JD Vance is in control of Elector Certificates and makes judicious use of outright fraudulent substitution, with the concurrence of enough state's delegations, he might be successful is manipulating the process to even though patently obvious, would, under the new rules of link:https://en.wikipedia.org/wiki/Electoral_Count_Reform_and_Presidential_Transition_Improvement_Act_of_2022["Presidential Reform Act of 2022," ,window=read-later,opts="noopener,nofollow" ] require a one-fifth concurring vote by the state's delegation to mount an objection, . Now the rule that was intended to avoid mischief could be used to prevent correcting an opening of fraudulent Elector Certificates (though the practical danger here is probably negligible, since there would need to be a state with a lar), also 
... There are still grounds to object to Electors which if pursued with enough scorched-earth politics may be sufficient to alter the election outcome, and crucially:
... *_There is a Constitutional threat bound up in the role of Vice President as President of the Senate: that of abdicating the role in order to prevent the Certification of any candidate on January 6th._* 
+
[8]
. The President and Vice-President Elect take Oaths of Office at noon on January 20th, becoming the President and Vice-President of the United States. 
.. In the most extreme of scenarios, there may be a plot to use the powers of homeland security or the military to assassinate the incoming President and Vice President and others in order to maintain control.
.. This is the infamous "Seal Team 6" hypothetical which was never answered by Supreme Court Justices who voted to give absolute immunity to a President who also has absolute authority to issue pardons. 

## Summary of Points of Failure 

[WARNING]
====
*Firstly:* 

Step 5 in <<The Points of Failure, Points of Failure>> means that Elector Certificates will be delivered during December 2028 to both the Archivist of the US (a MAGA regime appointee) and the Vice-President of the US. Both of these individuals face legal peril for their activities during the MAGA regime. 
 
Those Elector Certificates are vulnerable to alteration under the pretense that there was election rigging and therefore the Vice-President and/or the Archivist is rectifying the "problem" by "restoring" the "legitimate" (but actually fraudulent) Elector Certificates. 

Neither the link:https://constitution.congress.gov/constitution/amendment-12/["12th Amendment to the US Constitution", window=read-later,opts="noopener,nofollow"] nor the link:https://en.wikipedia.org/wiki/Electoral_Count_Reform_and_Presidential_Transition_Improvement_Act_of_2022["Presidential Reform Act of 2022," ,window=read-later,opts="noopener,nofollow" ] have any apparent method for reinstating correct Elector Certificates, only for refusing invalid ones through sustained objections.  

Therefore if MAGA actors are successful in having their altered or fake (ie, not reflecting the will of the voters) Elector Certificates opened by the Vice-President during the Joint Session on January 6th, 2029, Congress will be stuck with the dilemma of accepting them -- and electing the MAGA candidate -- or striking them (thereby reducing the number of Electors needed to elect the President) -- and electing the MAGA candidate. This would be a *_Constitutional Break_* because the obvious loser becomes the winner.  

*Secondly:* 

Step 7-a in <<The Points of Failure, Points of Failure>> presents a new hack that the MAGA regime can use to attempt to hold onto power. 

The Vice-President need only refuse to show up to preside over the Joint Session, and the nation will then be potentially powerless to appoint a successor president. This would be a *_Constitutional Break_* because it would leaving the current MAGA regime president in place indefinitely. 

*Finally:*

We must expect the MAGA regime to resort to these strategies because they will expect (rightly) criminal consequences for their actions once they lose power.  
====

## Defending

We will need to fight each of the <<The Points of Failure, Points of Failure>> above as follows:
[1] 
. Requires worrying about 3rd party candidates deliberately running in selected states to siphon off enough votes from the Democratic candidate to elect the the candidate for the MAGA regime. (ProjectLiberty2029 is "Democratic Party" focused because this is a practical set of proposals, and there is no other realistic hope for over-throwing the MAGA regime except with the other major political party that is non-Republican.) 
+
[2]
. There are two main strategies for fighting this: 
.. Work as hard as possible to make handling of the Elector Certificates a major 2026 election issue so as to elect as many Governors and Secretaries of State who are loyal to the US Constitution as possible, and 
.. Prepare teams to prosecute legal challenges if the Secretaries of State of any state are not actually reflecting the will of the people. If legal pressure meets with corrupted Judicial rulings, then it will ultimately require protests, civil disobedience and general strikes to bring as much pressure to bear on Secretaries of States to accurately report the will of the people. 
+
[3]
. Requires minimal attention since the only danger here are so called 'faithless' electors, which is unlikely to be a problem for the Democrats. If Secretaries of State have approved a MAGA regime candidate who in fact did not win, there would be an opportunity for Republican electors to accurately vote for the actual non-MAGA regime candidate. However, because the parties pick their own electors, this is such an unlikely scenario as to be unworthy of significant effort.
+
[4] 
. Requires monitoring the process with lawyers and grass roots organizations and Democratic party officials to insure that any loosing MAGA regime electors do not create Elector Certificates that satisfy the requirements of certification (such as signing them in the state's capital building, etc.) 
+
[5]
[5-a]
. Requires several robust actions by the 120th Congress (2027-2029), by the 121st Congress (2029-2031), and by the President and Vice-President Elect:
.. Because Elector Certificates are sent to Congress during November and December of 2028 (during the 120th Congress), and are vulnerable to tampering by bad-actors, there must therefore be passed during the 120th Congress a Simple Senate resolution that: footnote:[Note that Simple Resolutions do not require the President's approval, but they may only affect matters confined to the Congress, and they expire at the end of every Congress]
... Requires all incoming "transmissions, transfers, written communications, etc." to the Senate to be directed to the Secretary of the Senate, and 
... Requires the Secretary of the Senate to retain and safeguard any and all Elector Certificates transmitted to the Senate and/or to the President of the Senate under the 12th Amendment, and
... Requires the Sergeant of Arms of the Senate to safeguard the integrity of the handling by the Secretary of the Senate as necessary to safeguard the Elector Certificates, and 
... Prevents the President of the Senate (aka the Vice-President of the US) from taking control in any way of the Elector Certificates until the moment of opening dictated in the link:https://constitution.congress.gov/constitution/amendment-12/["12th Amendment to the US Constitution,", window=read-later,opts="noopener,nofollow"] and
... defends the constitutionality of this as a legitimate use of Congress' authority to determine its "Rules of its Proceeding" vested in the link:https://www.archives.gov/founding-docs/constitution-transcript["US Constitution Article I, Section 5, Clause 2.", window=read-later,opts="noopener,nofollow"]
+
[5-b]
.. The 121st Congress (2029-2031) must then Re-pass the Simple Resolution described under 5-a governing the handling of Elector Certificates in order to prevent the Vice-President from compromising the Elector Certificates, 
+
[5-c]
.. The 121st Congress must then Re-pass (and extend to both houses if only one had passed it before) the Simple Resolution described under 5-b granting security powers over the Capitol to the Sergeant of Arms of each of the two chambers,  
+
[5-d]
.. The President and President Elect must not treat a successful transition from the MAGA regime as a foregone conclusion. For the first time in our nation's history, this will be an open question. Therefore, the President and the Vice-President Elect must engage in political warfare including the following:
... Inspire the public in daily communications about the need and the virtue of respecting our Constitution, and respecting the Will of The People, and defending the integrity of the election, and 
... Debunking the lies and mis-information from the MAGA regime that claim the 2028 election was stolen, and
... Explaining MAGA subterfuges such as the creation of competing and false elector certificates, and 
... Use narrative stories of Americans who have seen the light of the mistakes of MAGA to further encourage the weakening of MAGA support and strengthening of public support, and
... Call on the public to come to Washington DC starting on the 2nd of January to act as a human shield against the plots of the MAGA regime to steal the election, and 
... Forego the tradition of waiting until January 20th to speak to the members of the current administration and actively reach out both in public, and where possible, in private to members of the following institutions with the following messages: 
.... Members of the military must remember their oaths to the Constitution, and their obligation to disobey illegal orders, and the promise that those who do so will be rewarded and those who do not will be prosecuted, and 
.... Members of the National Guard must remember the same, and 
.... Members of DOJ who are still loyal to the Constitution need to preserve records in accordance with the law and that now is the time they've been waiting for to put their valor to the test by working (in secret or in public) to help safeguard the government's transition to a post-MAGA regime, and
.... Members of the National Security apparatus who are still loyal to the Constitution; send the same message as to DOJ, and
.... Governors of both Red and Blue states, to coordinate policy and support from states led by Democratic governors, and to reassure Republican governors to the best extent possible that the incoming administration will respect checks-and-balances between the Federal govern and the states unless states are engaged in active un-constitutional support of MAGA. 
+
[6]
[6-a]
. Requires further robust actions by the 120th Congress, the 121st Congress, and the President and Vice-President Elect: 
.. Because logistics take time, and because the 120th Congress will be receiving Elector Certificates from the 2028 election, the 120th Congress must take steps to insure its security. Both chambers (it may be possible, but more difficult, to make an effective defense with only the authorization of one of the houses) must pass a Simple Resolution granting the Sergeant of Arms of each of the Chambers the authority to: footnote:[Note that Simple Resolutions do not require the President's approval, but they may only affect matters confined to the Congress, and they expire at the end of every Congress]
... Prepare for the defense of the Capitol against agents of the Administration, and 
... Prepare for the defense of the members of Congress from agents of the Administration, and 
... Specifically prepare for the defense of members of Congress against arrest on any charges of Treason, Felony, or Civil Violence unless such charges have been issued by a Grand Jury under due process and reviewed by the respective house of Congress where the member serves, and  
... Specifically allow the Capitol police to refuse to allow any entity other than the Capitol Police to effect arrest within Washington DC, as authorized by link:https://www.archives.gov/founding-docs/constitution-transcript["US Constitution Article I, Section 8, Clause 17, ", window=read-later,opts="noopener,nofollow"] which grants to Congress the right "to exercise exclusive Legislation in all Cases whatsoever" over the US Capitol district, and 
... To direct agents of the Capitol police to recover from custody any member of Congress arrested by agents of the Administration under charges of Treason or Felony or Civil Violence and present them for discipline to their respective House under the authority of link:https://www.archives.gov/founding-docs/constitution-transcript["US Constitution Article I, Section 5, Clause 2.", window=read-later,opts="noopener,nofollow"], and 
... To direct the Sergeant of Arms of each of the Houses of Congress to call for deployment of the National Guards of Maryland and Virginia to enter the Capitol district and assist the Capitol Police in any security needs, and to answer only to the respective Sergeant of Arms of the House and Senate and their State Governor, and to make such protection effective from the time of the November 7th election until further direction of the 121st Congress under the authority of link:https://www.archives.gov/founding-docs/constitution-transcript["US Constitution Article I, Section 8, Clause 17, ", window=read-later,opts="noopener,nofollow"], and
... To grant the Sergeant of Arms of each of the Houses of Congress the power to close streets, 
... To direct the Sergeant of Arms of each of the Houses of Congress to appropriate necessary temporary infrastructure (such as cafeterias, visitor centers, the Rotunda, etc) to house the Capitol Police on the grounds of the Capitol and have siege preparations that will last a minimum of one week without re-supply, and
... To begin contingency planning with the National Guards of Virginia and Maryland to resupply the Capitol Police and any civilian pro-democracy demonstrators if any siege of the Capitol should last longer than a week, where such planning must include provisions for:
.... Food & water,
.... Shelter and heat,
.... Production of electrical power independent of the electrical grid, 
.... Provision of emergency medical and fire response,
.... Access to communications infrastructure including cell-phone systems, microwave relay stations, and alternative satellite communications networks.
+
[6-b]
.. Address counter-moves by the MAGA regime as aggressively as possible, particularly after the nation has a President and Vice-President Elect, with whom the 120th Congress must coordinate responses to the mis-information and propaganda of the MAGA regime. 
+
[6-c]
.. The 121st Congress (2029-2031) must do the following:
... Re-Pass the Simple Resolutions in each house safeguarding Elector Certificates as described above under 5-a, and 
... Re-Pass the Simple Resolutions in each house empowering the Sergeant of Arms of each House and the Capitol police to safeguard the members of Congress as described above under 6-a.
... Plan to remain within the Capitol building to safeguard themselves and the Elector Certificates from January 3rd until January 6th. 
+
[6-d]
.. The President and President Elect must continue to do all the activities of 5-d above, and in addition, 
... They should be present in the separate but adjacent states of Virginia and Maryland and meet with the citizen volunteers who are going into the Capitol to safeguard the Congress, 
... They should coordinate with those volunteers and with grass-roots organizations, and with the States of Virginia and Maryland to support them with:
.... Training in non-violent resistance and de-escalation techniques, 
.... Providing them with food, water and tents, 
.... Providing them with communications support, 
.... Mapping out plans for health care in the case of emergencies,
.... Coordinating with the Capitol Police to support the Police, the Guard, and the pro-democracy supporters in a siege that may last over a week. 
+
[7]
[7-a]
. Unless the resistance to peaceful and orderly transfer of power by the pro-MAGA regime has crumbled at this point (which is a real possibility) further robust actions by the 121st Congress and the President and Vice-President Elect will be required: 
.. Members of Congress should expect to be at the center of a scene of siege that includes multiple layers of different powers answering to different command structures and loyal to two different goals (removal or retention of the MAGA regime), where the composition of these powers will likely include:
... Capitol Police, with the number of uniformed officers at approx 1,500 footnote:[link:https://en.wikipedia.org/wiki/United_States_Capitol_Police["Approx. 1,800 troops, ", window=read-later,opts="noopener,nofollow"] in total, and if we estimate 80-90% participation, that number is approximately 1,500] and positioned in and around the Capitol, on its grounds, and 
... Large numbers of unarmed pro-Democracy supporters, who will hopefully be positioned around the Capitol forces, camped out on the Mall and throughout the streets immediately around the capitol building, and
... At least two armed pro-Democracy National Guard Units numbering somewhere between 1,000 and 3,000 troops each, footnote:[Virginia has link:https://en.wikipedia.org/wiki/Virginia_Army_National_Guard["approx. 7,200 troops, ", window=read-later,opts="noopener,nofollow"] and Maryland has link:https://news.maryland.gov/ng/2023/04/08/governor-moore-appoints-brig-gen-janeen-l-birckhead-to-lead-the-maryland-military-department/["approx. 4,600 troops, ", , window=read-later,opts="noopener,nofollow"] not all of which will be available or needed] who will be hopefully positioned surrounding the pro-Democracy Supporters, and separating them from 
... MAGA loyalists including pardoned original January 6th rioters and insurrectionists, who probably number at lease 4,000 and should be assumed to be substantially armed, footnote:[link:https://en.wikipedia.org/wiki/January_6_United_States_Capitol_attack["The FBI estimated 2,000 to 2,500 ", window=read-later,opts="noopener,nofollow"] in the original January 6th assault, and so greater numbers should be expected], and 
... at least one MAGA loyal National Guard unit numbering possibly 600 troops and constituted under the authority of the link:https://www.whitehouse.gov/presidential-actions/2025/08/additional-measures-to-address-the-crime-emergency-in-the-district-of-columbia/["DJT August 25, 2025 Executive Order, ", window=read-later,opts="noopener,nofollow"] and
... MAGA loyalist Air Force and Marine units who provide a relatively small but significant helicopter presence, and 
... Possibly the MAGA President and his Secret Service Security detail attempting to address his supporters as close to the Capitol as possible, and
... Possibly the MAGA Vice-President and his Secret Service Security detail attempting to address his supporters as close to the Capitol as possible, and 
... An unknown number of civilians sheltering in place to avoid becoming casualties, and 
... An unknown number of infiltrators of each of the groups listed above by members of the other group with unknown intentions, and
... Hundreds of members of the news media including a significant number of single-actor 'podcasters.'
+
[7-b]
.. There is a substantial chance that events on the ground will spiral into unpredictable directions. Such unpredictability will likely lead to unnecessary tragedy. That is why the Capitol Police must have coordinated with the National Guard to have excess forces in place to create as calm a siege environment as possible in order to allow the most orderly and blood-free series of events to play out. 
+
[7-c]
.. The MAGA Vice-President will make a decision whether to attend the Joint Session as his duty requires, or not. History will likely turn sharply on this one decision. 
+
[7-d]
.. If the Vice-President *is attending,* then:
... There are even chances the outcome will be a successful Constitutional continuity:
... In case one, the Vice President may be planning on performing his ceremonial duties and facing defeat, for any combination of reasons, including: 
.... because he is capitulating to the righteousness of the demands of the vast majority of Americans, 
.... he realizes he will lose because of the preparations of Congress to uphold the Constitution, 
.... he hopes to save face, obtain mercy, and resurrect a career in politics post-MAGA, 
.... he has been unable to alter or substitute the Elector Certificates
... In the other case, the Vice President and members of his Party may be planning on attempting to subvert the election:
.... This will be possible if they have been able to alter or substitute fake Elector Certificates for a sufficient number of states to alter the outcome. 
.... If so, the response must be planned in advance, because under the terms of link:https://en.wikipedia.org/wiki/Electoral_Count_Reform_and_Presidential_Transition_Improvement_Act_of_2022["Presidential Reform Act of 2022, " ,window=read-later,opts="noopener,nofollow"] 
and the rules of link:https://www.govinfo.gov/content/pkg/USCODE-2024-title3/html/USCODE-2024-title3-chap1-sec15.htm["US Code Title 3, Section 15 (d) (2) (B) (i) ",window=read-later,opts="noopener,nofollow" ] all objections must be "In writing," *_and_* signed by one-fifth of Senators *_and_* Members of the House of Representatives. 
..... Congress must go State by State in alphabetical order, and must resolve objections one-by-one as determined by link:https://www.govinfo.gov/content/pkg/USCODE-2024-title3/html/USCODE-2024-title3-chap1-sec15.htm["US Code Title 3, Section 15 (d) (2) \(C) (ii) & Section 15 (d) (2) (D) ",window=read-later,opts="noopener,nofollow" ] 
..... This presents and advantage for any bad-actor who has been able to alter the Elector Certificates ahead of time:
...... They may have engineered, like a stacked deck of playing cards, the falsifying or not-falsifying of Elector Certificates so that the only way for Congress to preserve the Will of the People _in general_ will be to invalidate true Elector Certificates in order to further reduce the total number of eligible electors. footnote:[An example or two here is vital for understanding.] 
...... Only a complete modeling of all possibilities ahead of time (probably requiring mathematicians and computers) can guarantee the correct overall outcome.
...... However, even if the correct _overall_ outcome is achieved, this will constitute a *_Constitutional Break_* because voters were specifically disenfranchised at the level of entire states.
...... If this scenario plays out, then even if the correct _overall_ outcome of having the actually elected President and Vice President certified, it will work to the purposes of the MAGA regime in weakening faith in the US Constitution. 
[7-d]
.. If the Vice-President *is not attending,* then:
... The likely outcome will be a Constitutional Break, where extra-constitutional events unfold to install the winning President and Vice-President to their respective offices, but their legitimacy will forever be stained by not having achieved that outcome through standard Constitutional processes: 
... In this case the Vice-President will likely be speaking to the nation to attempt to sway public opinion to the idea that proceedings inside the building are illegitimate and calling for loyalty from party members inside to resist his removal as Vice-President, and
... Outside, with such a dizzying array of factions 
... Inside, Democrats will need to propose and prosecute the Impeachment of the Vice President on the grounds of Insurrection, dereliction of oath to the constitution, etc.. 
... The impeachment will probably pass, but
... The removal may not pass. 
.... If the Vice-President is removed by Impeachment, then a new standoff ensues: link:https://constitution.congress.gov/constitution/amendment-25/["the 25th Amendment to the Constitution, Section 2 ", window=read-later,opts="noopener,nofollow"] requires that the President nominate and a majority of both Houses of Congress approve a new Vice President. 
.... The President under these circumstances may choose not to nominate anyone, thus simply remaining in power. *_This is one Constitutional Break_* because it will mean that the President and Vice-President Elects were not confirmed on January 6th. 
.... The most Constitutional path forward from that point would probably be: 
..... The Congress Impeaches and removes the President (grounds could simply be his part in preventing the normal transition of power by refusing to nominate a Vice-President who is committed to the Constitution). This process may take quite a while, during which time the volatile situation out-side the Capitol may create unpredictable events on the ground. 
..... The length of this process is why the siege planning needs to be for at least a week.
..... Assuming the President is Impeached _and_ removed from office, things become Constitutionally clearer, but not in the way one might expect. With no President in place, the rules of the link:https://www.usa.gov/presidential-succession["US Constitution and Presidential Succession Act of 1947", window=read-later,opts="noopener,nofollow"] would install the Speaker of the House as the President. (This instantly removes the Speaker from Speakership as required by link:https://www.archives.gov/founding-docs/constitution-transcript["US Constitution Article I, Section 6, Clause 2.", window=read-later,opts="noopener,nofollow"])
..... In that case, the Will of the People in the Election in November would have been subverted.
..... *_This would be the second Constitutional Break._* 
..... With the best acting individuals, it would be possible to un-tangle the mess in the following way:
...... The President (former Speaker of the House) would nominate the original President Elect as Vice-President.
...... The House and Senate would approve that person as the new Vice President.
...... The President (former Speaker of the House) would resign the Presidency, and the Vice-President (former President Elect) would become President. 
...... The New President (the one actually elected by the People in November) would repeat the process for the original Vice-President Elect, and if approved by both Houses, now the leadership of the Administrative Branch matches the Will of the People expressed back in November. 
...... However, the Speaker of the House is out of the position to which he was elected (first by his constituents to the House, and then by his Caucus to Leadership.) 
...... The House would need to elect a new Speaker of the House. 
...... The former Speaker, former President would need to win a special election in his state, 
...... And then the Current Speaker of the House would need to Resign and the Caucus re-elect the original Speaker of the House. 
+
[8]
. If January 6th has been passed, then the period up until January 20th presents as more of a security issue. 
.. Because the security apparatus of the US has been compromised by the MAGA regime, the incoming President Elect should be protected not by Secret Service, but by National Guard and State Troopers from States whose Governors are working to preserve and protect the Constitution. 
.. This non-Secret Service protection should continue until the incoming post-MAGA Administration has been able to vet bad-actors from law enforcement and security services. 

## Summary of the defense

[.lead]
January 6th, 2029 is likely to see a repeat of a surrounded Capitol but at an exponentially larger scale. 
[.lead]
Competing mobs and competing units of the National Guard will settle the fate of whether the current US Constitution will continue without break, or be broken and need extra-Constitutional measures to reinstate. 

There need to be defensive resolutions by the House and Senate in the next congress (the 120th Congress, serving from 2027-2029) to avoid allowing the MAGA regime to perpetuate itself.  

These resolutions need to be done _by the next Congress_ or odds of a Constitutional Break increase dramatically. 

*The public must understand the significant stakes of the 2026 midterms for the presidential election in 2028.*

[NOTE]
====
The Simple Resolutions recommended for the Senate normally require a filibuster-proof majority.
====

[WARNING]
====
If the Democrats cannot win control of the Senate in 2026, they must attempt to find enough moderate Republicans to pass the resolutions controlling Elector Certificates and allowing safe-passage for members of the 121st Congress. 

If those resolutions cannot be passed, then the odds are strong there will be a Constitutional Break because the MAGA regime Vice-President will probably be both willing and able to manipulate the Elector Certification process to determine the 2028 election outcome during the Jan 6, 2029 session.  A secondary goal by the MAGA Vice-President would be to sow sufficient doubt and confusion into the process so as to weaken the over-all US Constitutional project.
====

