= First Lame Duck Session Dangers
:doctype: book
:table-caption: Data Set
:imagesdir: /Media/Images/
:page-authors: Vector Hasting
:page-draft_complete: 25%
:page-stage: 00
:page-todos:  
:showtitle:

= Who will be seated in the new congress?

There is a danger that the MAGA regime will not honor the will of the people during the 2026 midterm elections. 
link:https://www.thebulwark.com/p/dirty-procedural-move-house-republicans-election-denial-2026-midterms["This article on the Bulwark Substack," , window=read-later,opts="noopener,nofollow"] explores this topic in detail.

While this has historically happened when the elections were so close as to be statistical ties, now the world is different because the reality of the vote count itself is being questioned. 
This means that even if any reasonable person will agree that the vote count was not a tie but a clear win, the MAGA regime may simply declare some kind of fraud and proceed on such claims to throw out candidates from the opposing party.

While this seems a relatively low threat, it must be considered The only way to fight this is with political pressure. 
